image:
  name: hawkeye116477/pft2:latest
before_script:
  - git config --global user.email "PolishJarvis@int.pl"
  - git config --global user.name "PolishJarvis"
job:
  script: "./scripts/CI_LETS_DO_THIS_majkel.sh"
