image: polishfiltersteam/expired_domains_image:latest

stages:
  - check
  - final

CERT:
  stage: check
  script: "./scripts/CI/CI_LETS_DO_THIS_CERT.sh"
  artifacts:
    paths:
      - novelties/przekrety_CERT.txt

KAD:
  stage: check
  script: "./scripts/CI/CI_LETS_DO_THIS_KAD.sh"
  artifacts:
    paths:
      - expired-domains/KAD-expired.txt
      - expired-domains/KAD-unknown.txt

KADhosts:
  stage: check
  script: "./scripts/CI/CI_LETS_DO_THIS_KADhosts.sh"
  artifacts:
    paths:
      - expired-domains/KADhosts-expired.txt
      - expired-domains/KADhosts-unknown.txt

PAF:
  stage: check
  script:
    - "./scripts/CI/CI_LETS_DO_THIS_PAF.sh"
  artifacts:
    paths:
      - expired-domains/PAF_arrows-expired.txt
      - expired-domains/PAF_arrows-unknown.txt
      - expired-domains/PAF_backgrounds_self-advertising-expired.txt
      - expired-domains/PAF_backgrounds_self-advertising-unknown.txt
      - expired-domains/PAF_contact_feedback_widgets-expired.txt
      - expired-domains/PAF_contact_feedback_widgets-unknown.txt
      - expired-domains/PAF_newsletters-expired.txt
      - expired-domains/PAF_newsletters-unknown.txt
      - expired-domains/PAF_other_widgets-expired.txt
      - expired-domains/PAF_other_widgets-unknown.txt
      - expired-domains/PAF_pop-ups-expired.txt
      - expired-domains/PAF_pop-ups-unknown.txt
      - expired-domains/PAF_push-expired.txt
      - expired-domains/PAF_push-unknown.txt
      - expired-domains/PAF_scrolling_videos-expired.txt
      - expired-domains/PAF_scrolling_videos-unknown.txt

PAF_supp:
  stage: check
  script:
    - "./scripts/CI/CI_LETS_DO_THIS_PAF_supp.sh"
  artifacts:
    paths:
      - expired-domains/PAF_backgrounds_self-advertising_supp-expired.txt
      - expired-domains/PAF_backgrounds_self-advertising_supp-unknown.txt
      - expired-domains/PAF_newsletters_supp-expired.txt
      - expired-domains/PAF_newsletters_supp-unknown.txt
      - expired-domains/PAF_other_elements_supp-expired.txt
      - expired-domains/PAF_other_elements_supp-unknown.txt
      - expired-domains/PAF_pop-ups_supp-expired.txt
      - expired-domains/PAF_pop-ups_supp-unknown.txt
      - expired-domains/PAF_push_supp-expired.txt
      - expired-domains/PAF_push_supp-unknown.txt
      - expired-domains/PAF_scrolling_videos_supp-expired.txt
      - expired-domains/PAF_scrolling_videos_supp-unknown.txt
      - expired-domains/PAF_tagged_internal_links-expired.txt
      - expired-domains/PAF_tagged_internal_links-unknown.txt

RSS:
  stage: check
  script: "./scripts/CI/CI_LETS_DO_THIS_RSS.sh"
  artifacts:
    paths:
      - expired-domains/polish_rss_filters-expired.txt
      - expired-domains/polish_rss_filters-unknown.txt
      - expired-domains/polish_rss_filters_supp-expired.txt
      - expired-domains/polish_rss_filters_supp-unknown.txt

Social:
  stage: check
  script: "./scripts/CI/CI_LETS_DO_THIS_Social.sh"
  artifacts:
    paths:
      - expired-domains/adblock_social_list-expired.txt
      - expired-domains/adblock_social_list-unknown.txt

Social_supp:
  stage: check
  script: "./scripts/CI/CI_LETS_DO_THIS_Social_supp.sh"
  artifacts:
    paths:
      - expired-domains/social_filters_uB_AG-expired.txt
      - expired-domains/social_filters_uB_AG-unknown.txt

Cookies:
  stage: check
  script: "./scripts/CI/CI_LETS_DO_THIS_Cookies.sh"
  artifacts:
    paths:
      - expired-domains/adblock_cookies-expired.txt
      - expired-domains/adblock_cookies-unknown.txt

Cookies_supp:
  stage: check
  script: "./scripts/CI/CI_LETS_DO_THIS_Cookies_supp.sh"
  artifacts:
    paths:
      - expired-domains/cookies_uB_AG-expired.txt
      - expired-domains/cookies_uB_AG-unknown.txt

LWS:
  image: polishfiltersteam/lws_image:latest
  stage: check
  script: "./scripts/CI/CI_LETS_DO_THIS_LWS.sh"
  artifacts:
    paths:
      - novelties/podejrzane_LWS.txt

deploy:
  stage: final
  script: "./scripts/CI/cleanup_push.sh"
