image:
  name: hawkeye116477/pft2:latest


stages:
  - check
  - deploy

before_script:
  - git config --global user.email "PolishJarvis@int.pl"
  - git config --global user.name "PolishJarvis"

kad:
  stage: check
  script: "./scripts/CI_LETS_DO_THIS_kad.sh"
  artifacts:
    paths:
      - expired-domains/

kadhosts:
  stage: check
  script: "./scripts/CI_LETS_DO_THIS_kadHosts.sh"
  artifacts:
    paths:
      - expired-domains/

deploy:
  stage: deploy
  script: "./scripts/push.sh"
