dist: xenial
addons:
  apt:
    packages:
    - language-pack-pl
notifications:
  email:
    on_success: never
    on_failure: always
script:
- "./scripts/TRAVIS_LETS_DO_THIS.sh"
env:
  global:
    secure: M44l+6/BVw0hAacHKL6EhA/PQ7dQxmQvHRk0CYx5pAqzwI7oTp5nWiik1k0pszHT3m8Hrc3448iA0CYG7tRf1g6dYp7/7vSvK11SLTgH11wiPGaAR1Jv2VskW4c6Y6P7NvtAVHGuq/VtDvMvDRJKk/fYIGc/7wkk6iC7cxeGUIH0F0LGscVwiPSWLwOnq+uMlHDynQYG4qE4635RZ43476yhAY88aVh9aS2/ZWRI8l4oVT2I/unphCq3jQcWvUdAFJQk0vXzXuye2zndm/HKcafnGz3lL1UEUb0oqAH12lxg12vU1Rr+2MfN7CrMNS7j0okjqfOD96TsbZID1n9gpIolFw2N98whpCecB1Pssn7z3Nn2Mr/UOrsZu50wiULb+V1boabIAjcBzvVnjBbjDAKVGeSIc0QL1mtuT+lUTdkrxK2Q9Mwxs4kUKKDkq8WfKU7gQTWkGkbYkueuJls1ZLBftZeAby5qsl/a27VKA8iInSqZJKMVRfg4FNTir3O+84F9PvwCWbCOffG0Z/t69JfcHZ8o6Gd4l+HRio6eG8SIAa456eLDV/kBaPc/1C5CpV2MP9SFt8+uZ9cD28jclmJIhM35do8rVce8FYVx+ZWnq++VCSFXhdko4CJXfEtJk3vHH+iyrFRfipvlZpFjijJuhcHAkUrfSckRj3gwkHw=
