FROM polishfiltersteam/vichs_image:latest

RUN apt-get update && apt-get install -y software-properties-common
RUN apt-add-repository https://cli.github.com/packages
RUN apt-get update && apt-get install -y gh
RUN gh --version
