# https://github.com/CircleCI-Public/circleci-dockerfiles/blob/master/buildpack-deps/images/bionic/Dockerfile

FROM hawkeye116477/pft2:latest

RUN apt-get update && apt-get install -y python3-bs4 python3-certifi python3-urllib3
