version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:bionic
    steps:
      - checkout
      - run: apt-get update && apt-get install -y language-pack-pl
      - run: ./scripts/TRAVIS_LETS_DO_THIS.sh