version: 2
jobs:
  build:
    docker:
      - image: polishfiltersteam/vichs_image:latest
    steps:
      - checkout
      - run: ./scripts/HelperForVICHS.sh Test.txt Test_uBO_AG.txt
workflows:
  version: 2
  workflow:
    jobs:
      - build:
          context: org-global
