version: 2
jobs:
  build:
    docker:
      - image: hawkeye116477/pft:latest
    steps:
      - checkout
      - run: ./scripts/TRAVIS_LETS_DO_THIS.sh
workflows:
  version: 2
  workflow:
    jobs:
      - build:
          context: org-global
