version: 2
jobs:
  build:
    docker:
      - image: polishfiltersteam/vichs_image:latest
    steps:
      - checkout
      - run: ./scripts/VICHS_auto.sh
workflows:
  version: 2
  workflow:
    jobs:
      - build:
          context: org-global
