name: "Check Expired Domains From Filterlists"

on: workflow_dispatch
  # schedule:
  #   - cron: "55 23 * * 6"

jobs:
  KAD:
    runs-on: ubuntu-latest
    container: polishfiltersteam/expired_domains_image:latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2.3.4
      - run: |
          ./scripts/CI/CI_LETS_DO_THIS.sh https://raw.githubusercontent.com/PolishFiltersTeam/KAD/master/KAD.txt
          echo 'E_KAD<<EOF' >> $GITHUB_ENV
          echo "$(./scripts/CI/getFileListForED.sh KAD)" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - uses: actions/upload-artifact@v2.2.2
        with:
          name: E_KAD
          path: |
            ${{ env.E_KAD }}
  KADhosts:
    runs-on: ubuntu-latest
    container: polishfiltersteam/expired_domains_image:latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2.3.4
      - run: |
          ./scripts/CI/CI_LETS_DO_THIS.sh https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/sections/hostsplus.txt
          echo 'E_KADh<<EOF' >> $GITHUB_ENV
          echo "$(./scripts/CI/getFileListForED.sh KADhosts)" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - uses: actions/upload-artifact@v2.2.2
        with:
          name: E_KADh
          path: |
            ${{ env.E_KADh }}

  PAF:
    runs-on: ubuntu-latest
    container: polishfiltersteam/expired_domains_image:latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2.3.4
      - run: |
          ./scripts/CI/CI_LETS_DO_THIS.sh https://raw.githubusercontent.com/PolishFiltersTeam/PolishAnnoyanceFilters/master/PAF_arrows.txt https://raw.githubusercontent.com/PolishFiltersTeam/PolishAnnoyanceFilters/master/PAF_backgrounds_self-advertising.txt https://raw.githubusercontent.com/PolishFiltersTeam/PolishAnnoyanceFilters/master/PAF_contact_feedback_widgets.txt https://raw.githubusercontent.com/PolishFiltersTeam/PolishAnnoyanceFilters/master/PAF_newsletters.txt https://raw.githubusercontent.com/PolishFiltersTeam/PolishAnnoyanceFilters/master/PAF_other_widgets.txt https://raw.githubusercontent.com/PolishFiltersTeam/PolishAnnoyanceFilters/master/PAF_pop-ups.txt https://raw.githubusercontent.com/PolishFiltersTeam/PolishAnnoyanceFilters/master/PAF_push.txt https://raw.githubusercontent.com/PolishFiltersTeam/PolishAnnoyanceFilters/master/PAF_scrolling_videos.txt
          echo 'E_PAF<<EOF' >> $GITHUB_ENV
          echo "$(./scripts/CI/getFileListForED.sh PAF_arrows PAF_backgrounds_self-advertising PAF_contact_feedback_widgets PAF_newsletters PAF_other_widgets PAF_pop-ups PAF_push PAF_scrolling_videos)" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - uses: actions/upload-artifact@v2.2.2
        with:
          name: E_PAF
          path: |
            ${{ env.E_PAF }}
  PAF_supp:
    runs-on: ubuntu-latest
    container: polishfiltersteam/expired_domains_image:latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2.3.4
      - run: |
          ./scripts/CI/CI_LETS_DO_THIS.sh https://raw.githubusercontent.com/PolishFiltersTeam/PolishAnnoyanceFilters/master/PAF_backgrounds_self-advertising_supp.txt https://raw.githubusercontent.com/PolishFiltersTeam/PolishAnnoyanceFilters/master/PAF_tagged_internal_links.txt https://raw.githubusercontent.com/PolishFiltersTeam/PolishAnnoyanceFilters/master/PAF_newsletters_supp.txt https://raw.githubusercontent.com/PolishFiltersTeam/PolishAnnoyanceFilters/master/PAF_other_elements_supp.txt https://raw.githubusercontent.com/PolishFiltersTeam/PolishAnnoyanceFilters/master/PAF_pop-ups_supp.txt https://raw.githubusercontent.com/PolishFiltersTeam/PolishAnnoyanceFilters/master/PAF_push_supp.txt https://raw.githubusercontent.com/PolishFiltersTeam/PolishAnnoyanceFilters/master/PAF_scrolling_videos_supp.txt
          echo 'E_PAF_supp<<EOF' >> $GITHUB_ENV
          echo "$(./scripts/CI/getFileListForED.sh PAF_backgrounds_self-advertising_supp PAF_tagged_internal_links PAF_newsletters_supp PAF_other_elements_supp PAF_pop-ups_supp PAF_push_supp PAF_scrolling_videos_supp)" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - uses: actions/upload-artifact@v2.2.2
        with:
          name: E_PAF_supp
          path: |
            ${{ env.E_PAF_supp }}
  PASS:
    runs-on: ubuntu-latest
    container: polishfiltersteam/expired_domains_image:latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2.3.4
      - run: |
          ./scripts/CI/CI_LETS_DO_THIS.sh https://raw.githubusercontent.com/PolishFiltersTeam/PolishAntiAnnoyingSpecialSupplement/master/polish_rss_filters.txt https://raw.githubusercontent.com/PolishFiltersTeam/PolishAntiAnnoyingSpecialSupplement/master/sections/suplement.txt
          echo 'E_PASS<<EOF' >> $GITHUB_ENV
          echo "$(./scripts/CI/getFileListForED.sh polish_rss_filters polish_rss_filters_supp)" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - uses: actions/upload-artifact@v2.2.2
        with:
          name: E_PASS
          path: |
            ${{ env.E_PASS }}
  Social:
    runs-on: ubuntu-latest
    container: polishfiltersteam/expired_domains_image:latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2.3.4
      - run: |
          ./scripts/CI/CI_LETS_DO_THIS.sh https://raw.githubusercontent.com/PolishFiltersTeam/PolishSocialCookiesFiltersDev/master/adblock_social_filters/adblock_social_list.txt
          echo 'E_SOCIAL<<EOF' >> $GITHUB_ENV
          echo "$(./scripts/CI/getFileListForED.sh adblock_social_list)" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - uses: actions/upload-artifact@v2.2.2
        with:
          name: E_SOCIAL
          path: |
            ${{ env.E_SOCIAL }}
  Social_supp:
    runs-on: ubuntu-latest
    container: polishfiltersteam/expired_domains_image:latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2.3.4
      - run: |
          ./scripts/CI/CI_LETS_DO_THIS.sh https://raw.githubusercontent.com/PolishFiltersTeam/PolishSocialCookiesFiltersDev/master/adblock_social_filters/social_filters_uB_AG.txt
          echo 'E_SOCIAL_S<<EOF' >> $GITHUB_ENV
          echo "$(./scripts/CI/getFileListForED.sh social_filters_uB_AG)" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - uses: actions/upload-artifact@v2.2.2
        with:
          name: E_SOCIAL_S
          path: |
            ${{ env.E_SOCIAL_S }}

  Cookies:
    runs-on: ubuntu-latest
    container: polishfiltersteam/expired_domains_image:latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2.3.4
      - run: |
          ./scripts/CI/CI_LETS_DO_THIS.sh https://raw.githubusercontent.com/PolishFiltersTeam/PolishSocialCookiesFiltersDev/master/cookies_filters/adblock_cookies.txt
          echo 'E_COOKIES<<EOF' >> $GITHUB_ENV
          echo "$(./scripts/CI/getFileListForED.sh adblock_cookies)" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - uses: actions/upload-artifact@v2.2.2
        with:
          name: E_COOKIES
          path: |
            ${{ env.E_COOKIES }}
  Cookies_supp:
    runs-on: ubuntu-latest
    container: polishfiltersteam/expired_domains_image:latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2.3.4
      - run: |
          ./scripts/CI/CI_LETS_DO_THIS.sh https://raw.githubusercontent.com/PolishFiltersTeam/PolishSocialCookiesFiltersDev/master/cookies_filters/cookies_uB_AG.txt
          echo 'E_COOKIES_S<<EOF' >> $GITHUB_ENV
          echo "$(./scripts/CI/getFileListForED.sh cookies_uB_AG)" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - uses: actions/upload-artifact@v2.2.2
        with:
          name: E_COOKIES_S
          path: |
            ${{ env.E_COOKIES_S }}
  KAD_limit:
    needs:
      [
        KAD,
        KADhosts,
        PAF,
        PAF_supp,
        PASS,
        Social,
        Social_supp,
        Cookies,
        Cookies_supp,
      ]
    runs-on: ubuntu-latest
    container: polishfiltersteam/expired_domains_image:latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2.3.4
      - uses: actions/download-artifact@v2.0.8
        with:
          path: expired-domains
      - run: |
          ./scripts/CI/CI_LETS_DO_THIS_KAD_limit.sh
          echo 'E_KAD<<EOF' >> $GITHUB_ENV
          echo "$(./scripts/CI/getFileListForED.sh KAD)" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - uses: actions/upload-artifact@v2.2.2
        with:
          name: E_KAD
          path: |
            ${{ env.E_KAD }}
  deploy:
    needs: [KAD_limit]
    runs-on: ubuntu-latest
    container: polishfiltersteam/expired_domains_image:latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2.3.4
      - uses: actions/download-artifact@v2.0.8
        with:
          path: expired-domains
      - run: ./scripts/CI/cleanup_push.sh
