name: "Check Expired Domains From Filterlists"

on:
  workflow_dispatch
  # schedule:
  #   - cron: "55 23 * * 6"

jobs:
  KAD:
    runs-on: ubuntu-latest
    container: polishfiltersteam/expired_domains_image:latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2
      - run: |
          ./scripts/CI/CI_LETS_DO_THIS.sh KAD
          echo 'E_KAD<<EOF' >> $GITHUB_ENV
          echo "$(./scripts/CI/getFileListForED.sh KAD)" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - uses: actions/upload-artifact@v2
        with:
          name: E_KAD
          path: |
            ${{ env.E_KAD }}
  KADhosts:
    runs-on: ubuntu-latest
    container: polishfiltersteam/expired_domains_image:latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2
      - run: |
          ./scripts/CI/CI_LETS_DO_THIS.sh KADhosts
          echo 'E_KADH<<EOF' >> $GITHUB_ENV
          echo "$(./scripts/CI/getFileListForED.sh KADhosts)" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - uses: actions/upload-artifact@v2
        with:
          name: E_KADH
          path: |
            ${{ env.E_KADH }}

  PAF:
    runs-on: ubuntu-latest
    container: polishfiltersteam/expired_domains_image:latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2
      - run: |
          ./scripts/CI/CI_LETS_DO_THIS.sh PAF
          echo 'E_PAF<<EOF' >> $GITHUB_ENV
          echo "$(./scripts/CI/getFileListForED.sh \
          PAF_arrows \
          PAF_backgrounds_self-advertising \
          PAF_contact_feedback_widgets \
          PAF_e_newspaper \
          PAF_newsletters \
          PAF_other_widgets \
          PAF_pop-ups \
          PAF_push \
          PAF_scrolling_videos)" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - uses: actions/upload-artifact@v2
        with:
          name: E_PAF
          path: |
            ${{ env.E_PAF }}
  PAF_supp:
    runs-on: ubuntu-latest
    container: polishfiltersteam/expired_domains_image:latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2
      - run: |
          ./scripts/CI/CI_LETS_DO_THIS.sh PAF_supp
          echo 'E_PAF_supp<<EOF' >> $GITHUB_ENV
          echo "$(./scripts/CI/getFileListForED.sh \
          PAF_backgrounds_self-adv_supp \
          PAF_comeback_titles \
          PAF_contact_feedback_widgets_supp \
          PAF_newsletters_supp \
          PAF_other_elements_supp \
          PAF_pop-ups_supp \
          PAF_push_supp \
          PAF_scrolling_videos_supp \
          PAF_tagged_internal_links)" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - uses: actions/upload-artifact@v2
        with:
          name: E_PAF_S
          path: |
            ${{ env.E_PAF_S }}
  PASS:
    runs-on: ubuntu-latest
    container: polishfiltersteam/expired_domains_image:latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2
      - run: |
          ./scripts/CI/CI_LETS_DO_THIS.sh PASS
          echo 'E_PASS<<EOF' >> $GITHUB_ENV
          echo "$(./scripts/CI/getFileListForED.sh polish_rss_filters polish_rss_filters_supp)" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - uses: actions/upload-artifact@v2
        with:
          name: E_PASS
          path: |
            ${{ env.E_PASS }}
  Social:
    runs-on: ubuntu-latest
    container: polishfiltersteam/expired_domains_image:latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2
      - run: |
          ./scripts/CI/CI_LETS_DO_THIS.sh Social
          echo 'E_SOCIAL<<EOF' >> $GITHUB_ENV
          echo "$(./scripts/CI/getFileListForED.sh adblock_social_list)" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - uses: actions/upload-artifact@v2
        with:
          name: E_SOCIAL
          path: |
            ${{ env.E_SOCIAL }}
  Social_supp:
    runs-on: ubuntu-latest
    container: polishfiltersteam/expired_domains_image:latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2
      - run: |
          ./scripts/CI/CI_LETS_DO_THIS.sh Social_supp
          echo 'E_SOCIAL_S<<EOF' >> $GITHUB_ENV
          echo "$(./scripts/CI/getFileListForED.sh social_filters_uB_AG)" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - uses: actions/upload-artifact@v2
        with:
          name: E_SOCIAL_S
          path: |
            ${{ env.E_SOCIAL_S }}

  Cookies:
    runs-on: ubuntu-latest
    container: polishfiltersteam/expired_domains_image:latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2
      - run: |
          ./scripts/CI/CI_LETS_DO_THIS.sh Cookies
          echo 'E_COOKIES<<EOF' >> $GITHUB_ENV
          echo "$(./scripts/CI/getFileListForED.sh adblock_cookies)" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - uses: actions/upload-artifact@v2
        with:
          name: E_COOKIES
          path: |
            ${{ env.E_COOKIES }}
  Cookies_supp:
    runs-on: ubuntu-latest
    container: polishfiltersteam/expired_domains_image:latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2
      - run: |
          ./scripts/CI/CI_LETS_DO_THIS.sh Cookies_supp
          echo 'E_COOKIES_S<<EOF' >> $GITHUB_ENV
          echo "$(./scripts/CI/getFileListForED.sh cookies_uB_AG)" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - uses: actions/upload-artifact@v2
        with:
          name: E_COOKIES_S
          path: |
            ${{ env.E_COOKIES_S }}
  KAD_limit:
    needs:
      [
        KAD,
        KADhosts,
        PAF,
        PAF_supp,
        PASS,
        Social,
        Social_supp,
        Cookies,
        Cookies_supp,
      ]
    runs-on: ubuntu-latest
    container: polishfiltersteam/expired_domains_image:latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2
      - uses: actions/download-artifact@v2
        with:
          name: E_KAD
          path: expired-domains
      - run: |
          ./scripts/CI/CI_LETS_DO_THIS_KAD_limit.sh
          echo 'E_KAD<<EOF' >> $GITHUB_ENV
          echo "$(./scripts/CI/getFileListForED.sh KAD)" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - uses: actions/upload-artifact@v2
        with:
          name: E_KAD
          path: |
            ${{ env.E_KAD }}
  deploy:
    needs: [KAD_limit]
    runs-on: ubuntu-latest
    container: polishfiltersteam/expired_domains_image:latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2
      ## See https://github.com/actions/download-artifact/issues/68
      ## Unfortunately currently it's not possible to skip creating extra directory
      ## when we want to download all artifacts at once without specyfing name.
      ## Bad joke...
      - uses: actions/download-artifact@v2
        with:
          name: E_KAD
          path: expired-domains
      - uses: actions/download-artifact@v2
        with:
          name: E_KADH
          path: expired-domains
      - uses: actions/download-artifact@v2
        with:
          name: E_PAF
          path: expired-domains
      - uses: actions/download-artifact@v2
        with:
          name: E_PAF_S
          path: expired-domains
      - uses: actions/download-artifact@v2
        with:
          name: E_PASS
          path: expired-domains
      - uses: actions/download-artifact@v2
        with:
          name: E_SOCIAL
          path: expired-domains
      - uses: actions/download-artifact@v2
        with:
          name: E_SOCIAL_S
          path: expired-domains
      - uses: actions/download-artifact@v2
        with:
          name: E_COOKIES
          path: expired-domains
      - uses: actions/download-artifact@v2
        with:
          name: E_COOKIES_S
          path: expired-domains
      - run: ./scripts/CI/cleanup_push.sh
