name: "Check Expired Domains From Filterlists"

on:
  workflow_dispatch:
    inputs:
      number_of_KAD_jobs:
        description: "Quantity of KAD jobs"
        required: true
        default: 4
      number_of_KADh_jobs:
        description: "Quantity of KADhosts jobs"
        required: true
        default: 2
  # schedule:
  #   - cron: "55 23 * * 6"
env:
  CI_TIME_LIMIT: "2 hours"
  NUMBER_OF_KAD_JOBS: ${{ github.event.inputs.number_of_kad_jobs || 4 }}
  NUMBER_OF_KADHOSTS_JOBS: ${{ github.event.inputs.number_of_KADh_jobs || 2 }}

jobs:
  KAD_S:
    runs-on: ubuntu-latest
    container: ghcr.io/filtersheroes/expired_domains_image:latest
    outputs:
      KAD-strategy-matrix: ${{ steps.generate.outputs.KAD-strategy-matrix }}
      KADh-strategy-matrix: ${{ steps.generate.outputs.KADh-strategy-matrix }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          echo "$NUMBER_OF_KAD_JOBS"
          numberParts="$NUMBER_OF_KAD_JOBS" ./scripts/CI/CI_LETS_DO_THIS.py KAD
          numberParts="$NUMBER_OF_KADHOSTS_JOBS" ./scripts/CI/CI_LETS_DO_THIS.py KADhosts
      - uses: actions/upload-artifact@v4
        with:
          name: E_KAD_S
          path: |
            split/KAD_*
      - uses: actions/upload-artifact@v4
        with:
          name: E_KADH_S
          path: |
            split/KADhosts_*
      - id: generate
        run: |
          ./scripts/CI/createMatrixStrategy.py
  KAD:
    needs: [KAD_S, PAF, SocialPASS, Cookies, KADhosts]
    runs-on: ubuntu-latest
    container: ghcr.io/filtersheroes/expired_domains_image:latest
    strategy:
      matrix:
        KAD: ${{ fromJson(needs.KAD_S.outputs.KAD-strategy-matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: E_KAD_S
          path: split
      - run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          KADfile=KAD_"$(./scripts/CI/getFileNumber.sh ${{ matrix.KAD }} )"
          ./scripts/CI/CI_LETS_DO_THIS.py "$KADfile"
          echo 'E_KADS<<EOF' >> $GITHUB_ENV
          echo "$(./scripts/CI/getFileListForED.sh $KADfile)" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          echo "currentKADName=E_$KADfile" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.currentKADName }}
          path: |
            ${{ env.E_KADS }}
  KADhosts:
    needs: KAD_S
    runs-on: ubuntu-latest
    container: ghcr.io/filtersheroes/expired_domains_image:latest
    strategy:
      matrix:
        KADH: ${{ fromJson(needs.KAD_S.outputs.KADh-strategy-matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: E_KADH_S
          path: split
      - run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          KADHfile=KADhosts_"$(./scripts/CI/getFileNumber.sh ${{ matrix.KADH }} )"
          ./scripts/CI/CI_LETS_DO_THIS.py "$KADHfile"
          echo 'E_KADHS<<EOF' >> $GITHUB_ENV
          echo "$(./scripts/CI/getFileListForED.sh $KADHfile)" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          echo "currentKADHName=E_$KADHfile" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.currentKADHName }}
          path: |
            ${{ env.E_KADHS }}
  PAF:
    runs-on: ubuntu-latest
    container: ghcr.io/filtersheroes/expired_domains_image:latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          ./scripts/CI/CI_LETS_DO_THIS.py PAF_C
          echo 'E_PAF<<EOF' >> $GITHUB_ENV
          echo "$(./scripts/CI/getFileListForED.sh \
          PAF_arrows \
          PAF_backgrounds_self-advertising \
          PAF_contact_feedback_widgets \
          PAF_e_newspaper \
          PAF_newsletters \
          PAF_other_widgets \
          PAF_pop-ups \
          PAF_push \
          PAF_scrolling_videos \
          PAF_backgrounds_self-adv_supp \
          PAF_comeback_titles \
          PAF_contact_feedback_widgets_supp \
          PAF_newsletters_supp \
          PAF_other_elements_supp \
          PAF_pop-ups_supp \
          PAF_push_supp \
          PAF_scrolling_videos_supp \
          PAF_tagged_internal_links)" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - uses: actions/upload-artifact@v4
        with:
          name: E_PAF
          path: |
            ${{ env.E_PAF }}
  SocialPASS:
    runs-on: ubuntu-latest
    container: ghcr.io/filtersheroes/expired_domains_image:latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          ./scripts/CI/CI_LETS_DO_THIS.py Social_C
          ./scripts/CI/CI_LETS_DO_THIS.py PASS
          echo 'E_SOCIAL<<EOF' >> $GITHUB_ENV
          echo "$(./scripts/CI/getFileListForED.sh polish_rss_filters polish_rss_filters_supp adblock_social_list social_filters_uB_AG)" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - uses: actions/upload-artifact@v4
        with:
          name: E_SOCIAL
          path: |
            ${{ env.E_SOCIAL }}
  Cookies:
    runs-on: ubuntu-latest
    container: ghcr.io/filtersheroes/expired_domains_image:latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          ./scripts/CI/CI_LETS_DO_THIS.py Cookies_C
          echo 'E_COOKIES<<EOF' >> $GITHUB_ENV
          echo "$(./scripts/CI/getFileListForED.sh adblock_cookies cookies_uB_AG)" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - uses: actions/upload-artifact@v4
        with:
          name: E_COOKIES
          path: |
            ${{ env.E_COOKIES }}
  KAD_limit:
    needs: [KAD]
    runs-on: ubuntu-latest
    container: ghcr.io/filtersheroes/expired_domains_image:latest
    steps:
      - uses: actions/checkout@v4
      - continue-on-error: true
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          ./scripts/CI/getArtifactNamesForED.py KAD
      - uses: hawkeye116477/download-multiple-artifacts-action@v2
        with:
          names: |
            ${{ env.E_KAD_NAMES }}
          path: expired-domains
      - run: |
          ./scripts/CI/CI_LETS_DO_THIS_KAD_limit.py
          echo 'E_KAD<<EOF' >> $GITHUB_ENV
          echo "$(./scripts/CI/getFileListForED.sh KAD)" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - uses: actions/upload-artifact@v4
        with:
          name: E_KAD
          path: |
            ${{ env.E_KAD }}
  deploy:
    needs: [KAD_limit, KADhosts, PAF, SocialPASS, Cookies]
    runs-on: ubuntu-latest
    container: ghcr.io/filtersheroes/expired_domains_image:latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - continue-on-error: true
        run: ./scripts/CI/getArtifactNamesForED.py KADhosts
      - continue-on-error: true
        uses: hawkeye116477/download-multiple-artifacts-action@v2
        with:
          names: |
            ${{ env.E_KADhosts_NAMES }}
            E_KAD
            E_PAF
            E_SOCIAL
            E_COOKIES
          path: expired-domains
      - name: "Final deploy"
        env:
          GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          ./scripts/CI/deploy.py
