name: Closed Issue Labeler

on:
  issues:
    types: [closed]

jobs:
  apply-label:
    if: github.event.label.name == 'zatwierdzone' || github.event.label.name == 'wontfix'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: hawkeye116477/issue-manager-action@main
        with:
          mode: "labelClosed"
          completed-label: "zatwierdzone"
          not-planned-label: "wontfix"
