name: Doorman

on:
  issues:
    types: [labeled]

jobs:
  close:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: hawkeye116477/issue-manager-action@main
        with:
          mode: "close"
          completed-label: "zatwierdzone"
          not-planned-label: "wontfix"
 