name: "Remove Expired Domains From Filterlists"

on:
  workflow_dispatch:
  schedule:
    - cron: "55 23 * * 0"
jobs:
  letsgo:
    runs-on: ubuntu-latest
    container: ghcr.io/filtersheroes/expired_domains_image:latest
    strategy:
      matrix:
        repo: ["KAD", "KADhosts", "PolishAnnoyanceFilters", "PolishAntiAnnoyingSpecialSupplement", "PolishSocialCookiesFiltersDev"]
    steps:
      - uses: actions/checkout@v4
        with:
          path: ScriptsPlayground
          persist-credentials: false
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/${{ matrix.repo }}
          path: ${{ matrix.repo }}
          persist-credentials: false
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: 994739
          private-key: ${{ secrets.PRIVATE_APP_HELPER_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: ${{ matrix.repo }}
      - name: Get GitHub App User Info
        uses: octokit/request-action@v2.x
        id: get-user-info
        with:
          route: GET /users/${{ steps.app-token.outputs.app-slug }}[bot]
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
      - env:
          GIT_TOKEN: ${{ steps.app-token.outputs.token }}
          CI_USERNAME: ${{ steps.app-token.outputs.app-slug }}[bot]
          CI_EMAIL: ${{ fromJson(steps.get-user-info.outputs.data).id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          python3 ./ScriptsPlayground/scripts/CI/CI_removeExpiredDomains.py "${{matrix.repo}}"
