name: "Test downloading artifacts"

on:
  workflow_dispatch:
    inputs:
      number_of_KAD_jobs:
        description: "Quantity of KAD jobs"
        required: true
        default: 3

jobs:
  generate-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          cd "$GITHUB_WORKSPACE"
          mkdir ./expired-d
          touch ./expired-d/test-1.txt
          touch ./expired-d/test-2.txt
          touch ./expired-d/test-3.txt
      - uses: actions/upload-artifact@v3
        with:
          name: E_KAD_01
          path: |
            expired-d/test-1.txt
      - uses: actions/upload-artifact@v3
        with:
          name: E_KAD_02
          path: |
            expired-d/test-2.txt
      - uses: actions/upload-artifact@v3
        with:
          name: E_KAD_03
          path: |
            expired-d/test-3.txt
  download-artifacts:
    needs: generate-artifacts
    runs-on: ubuntu-latest
    container: ghcr.io/filtersheroes/expired_domains_image:latest
    steps:
      - uses: actions/checkout@v4
      - env:
          GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          ./scripts/CI/downloadArtifacts.py "KAD" "$GITHUB_WORKSPACE/expired-d"
          ls -l ./expired-d
