name: "Test downloading artifacts"

on:
  workflow_dispatch:
    inputs:
      number_of_jobs:
        description: "Quantity of KAD jobs"
        required: true
        default: 4
env:
  NUMBER_OF_JOBS: ${{ github.event.inputs.number_of_jobs || 4 }}

jobs:
  generate-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          cd "$GITHUB_WORKSPACE"
          mkdir ./expired-d
          touch ./expired-d/test-1.txt
          touch ./expired-d/test-2.txt
          touch ./expired-d/test-3.txt
          touch ./expired-d/test-4.txt
          touch ./expired-d/test-5.txt
      - uses: actions/upload-artifact@v5
        with:
          name: E_KAD_01
          path: |
            expired-d/test-1.txt
      - uses: actions/upload-artifact@v5
        with:
          name: E_KAD_02
          path: |
            expired-d/test-2.txt
      - uses: actions/upload-artifact@v5
        with:
          name: E_KAD_03
          path: |
            expired-d/test-3.txt
      - uses: actions/upload-artifact@v5
        with:
          name: E_KAD_04
          path: |
            expired-d/test-4.txt
      - uses: actions/upload-artifact@v5
        with:
          name: E_KAD_05
          path: |
            expired-d/test-5.txt
  download-artifacts:
    needs: generate-artifacts
    runs-on: ubuntu-latest
    container: ghcr.io/filtersheroes/expired_domains_image:latest
    steps:
      - uses: actions/checkout@v5
      - uses: hawkeye116477/download-multiple-artifacts-action@v2
        with:
          names: |
            E_KAD_01
            E_KAD_02
            E_KAD_03
            E_KAD_04
            E_KAD_05
          path: expired-d
      - run: |
          ls -l ./expired-d
